---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: brotherlogic-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      copr:
        - atim/starship
        - chronoscrat/devpod
        - a-zhn/ghostty
        - solopasha/hyprland
    install:
      packages:
        - micro
        - starship
        - emacs
        - devpod
        - hyprland
        - swaybg
        - ghostty
        - gh
        - cdparanoia
        - docker
        - golang
        - nodejs
        - npm
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
          - io.podman_desktop.PodmanDesktop
          - com.google.Chrome
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: rpm-ostree
    repos:
      -  antigravity.repo
      -  vscode.repo
    install:
      - antigravity
      - code

  - type: script
    snippets:
      - "curl -Lo /usr/bin/talosctl https://github.com/siderolabs/talos/releases/latest/download/talosctl-linux-amd64"
      - "chmod +x /usr/bin/talosctl"
      - "git clone https://github.com/brotherlogic/devcontainer-manager.git /tmp/devcontainer-manager"
      - "cd /tmp/devcontainer-manager && go build -o /usr/bin/devcontainer-manager main.go"
      - "sed -e 's/\\\\|/|/g' -e 's|%PROJECT_DIR%|%h/devcontainer-manager|g' -e 's|%GO_CMD%|/usr/bin/go|g' /tmp/devcontainer-manager/service-file > /usr/lib/systemd/user/devcontainer-manager.service"
      - "systemctl --global enable devcontainer-manager.service"
      - "mkdir -p /usr/share/backgrounds && curl -L 'https://fedoraproject.org/w/uploads/1/1c/F43-DAY_final_day_%28small%29.png' -o /usr/share/backgrounds/f43-day.png"
      - "npm install -g @google/gemini-cli"

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /